### ISSUE TITLE
Feature Request: Multi-Window targets

### ISSUE THREAD

**Issue by ziontee113** [woosaaahh/sj.nvim#16]
Hi @woosaaahh , thank you for the awesome plugin :+1: 

It would be amazing if we can have use sj.nvim to search and jump to different windows. I used to use Hop for this task, but I think I'll switch to sj.nvim from now on.

Is this feature planned? It would be so amazing :smile:

**Comment by ziontee113** [comment]
Now I think of it, it will be quite problematic since more windows == more targets == not enough labels :thinking: (if we want to keep the labels single-character)

**Comment by woosaaahh** [comment]
I think it would be very useful to have this feature !

Some ideas I have so far : 

- add a `multi_windows` option for `sj.run()` ;
- restrict multi windows targets to visible lines in each windows ;
- enhance labels handling to still have a minimal and predictable number of keys to type but to avoid having not enough labels. I run out of labels recently and that's not good ;
- using window label before match label (`plu:ac`, `plu:bc`, `plu:cc`, ...).
I think your idea is really good but IMHO using window label before will feel more natural. 

I'm still thinking about all of this and how to implement it. 
My main goal for the plugin is simplicity with enough flexibility.

**Comment by ziontee113** [comment]
That's awesome 👍 I can't wait to see multi window gets implemented.

**Comment by woosaaahh** [comment]
@ziontee113 Hi ! I added a new feature here b484688ae376c7755ed52bb89290b8ea556041ad (only on branch `0.6`).

As said in the commit message, you can now select the window that will be used for the search and you can also jump to a window without starting a search.

I really tried to have the live search done in all windows at the same time but had a lot of issues with highlights.

So for now, instead of a multi windows live search, I propose to select the window that will be used for the search.

This feature was easier to implement than the multi windows search and IMHO, can still help to improve the navigation.

The code below is an extract of the README.md that shows how the feature can be used.

```lua
vim.keymap.set("n", "!", function()
  sj.run({ select_window = true })
end)

vim.keymap.set("n", "<A-!>", function()
  sj.select_window()
end)
```
 
When the keymap in the first example is triggered : 

1. labels will be displayed in each corners of each windows
2. you type the label corresponding to the window you want to select 'a', 'b', 'c', ... (just one character, no need to validate with Enter)
3. you type the pattern to search

![sj_nvim-select_window](https://user-images.githubusercontent.com/111681540/198820372-6f942f1d-a589-422c-9888-251ba6cdc141.gif)

I hope it will help !

**Comment by ziontee113** [comment]
Thanks a lot! I'll definitely check it out ☺️

**Comment by woosaaahh** [comment]
Feel free to come back here and give any feedback , please !

**Comment by ziontee113** [comment]
Hi @woosaaahh , thank you very much on the hard work you put into this plugin, from creating it to continuing developing it's new features.
My feedback will be at a personal level, so please take it with a grain of salt.

A while ago I stumbled across your plugin. At that state in time, the experience was "stealthy". There was almost no visual display happen to the buffer, only the `abcd...` labels, which I really enjoyed. I mapped `separator` to `<space>` and had a good time with it.

A few days ago, I updated my plugins, and my `sj.nvim` experience changed. With the additional highlights, it broke the "stealthyness" that I loved from the earlier version. But the change that got me to stop using `sj.nvim` was that instead of keeping the buffer view intact, the buffer view moved when I search for patterns that is my `scrolloff` zone. So I stopped using `sj.nvim` since then.

Now back to the multi-window jump feature. Since I've received your message I reinstalled `sj.nvim` to test out the new multi-win function. After some testing, I'd say that the mental overhead of having to pick the window beforehand is just too great. 

When you want to search for something you think of the pattern first, then the matches, not the way around. Having to process which window to jump to is too much mental overhead, and would ruin the experience immediately.

Although it's a very interesting approach. I don't think it's the right one to tackle this issue :+1:

**Comment by woosaaahh** [comment]
> There was almost no visual display happen to the buffer, only the abcd... labels, which I really enjoyed

I'm not really sure what do you mean but you can remove some UI annoyance with `user_overlay = false` and `prompt_prefix = ""` in the global configuration.

For the highlights, maybe setting all of them to the same style or maybe just not overriding them might help.

If you tell me what annoys you, I can add options to disable them or maybe add a "stealthy" mode that will have minimal visuals !

> But the change that got me to stop using sj.nvim was that instead of keeping the buffer view intact, the buffer view moved when I search for patterns that is my scrolloff zone.

When you start a search, the label for the first match is focused and the cursor jump to it which is what cause the shift. 

If this what you're talking about, I also find it annoying especially with "visible_lines" scope.

As I don't use scrolloffs, I never noticed that it is more annoying than I thought.

What I propose it to keep the auto focus feature (the focused label has a different color than other labels) 
but enable the moving cursor only for the "buffer" scope.

---

About this issue, the 'select window' is a quick way for me to search in other windows and was easier to implement.

I'm still interested to have a multi window live search but it's a bit more complicated than I thought with the current code.

I have to refactor a lot because everything was badly designed for one buffer only.

---

Thanks for the feedbacks, I really appreciate them !

**Comment by ziontee113** [comment]
That's the problem. This plug-in is excellent for buffer only movement. You did a great job at that.

**Comment by ziontee113** [comment]
@woosaaahh I wonder what's your schedule looks like. If possible, I'd love to develop plugins with you 👍

**Comment by woosaaahh** [comment]
@ziontee113 I just pushed the ['feat-multi_wins_search' branch](https://github.com/woosaaahh/sj.nvim/tree/feat-multi_wins_search)

So far, it works pretty well as you proposed in your [second post](https://github.com/woosaaahh/sj.nvim/issues/16#issuecomment-1272287991).

The thing that bothers me right now is the case when a part of a buffer is visible in multiple windows.

For the same visible lines/content, the labels for the latest windows overlap the labels for the oldest windows.

I checked with Leap and Hop and they have the same "issue".

However with the SJ you can still define/force wich window you want to jump in.

Here is an example with only 1 buffer but 4 windows and parts of the buffer that are visible in other windows. 
From Neovim, windows are ordered like this
```
 A | C
---+---
 B | D
```
If you check the upper labels with the lower labels for windows A, B and C; you'll notice that the labels for the next window are visible at the end of the previous window.

![multi_wins-1](https://user-images.githubusercontent.com/111681540/198862277-cff74058-6670-407d-9eae-89d72fac7a00.png)

As you can still jump to the window you want, I don't know if that's really an issue.
(We can easily invert this behavior and have oldest window labels overlaping newest window labels)

If you use this keymap sample (extracted from the README) 
```lua
vim.keymap.set({ "n", "o", "x" }, "gs", function()
  sj.run({ multi_windows = true })
end)
```
you can have this keys sequence
```lua
keymap + pattern  + separator + label + window label
  gs       op          :          a        c

--> gsop:ac
```
---

Btw, I (think) I have fixed the view shifting issue. I tried with `scrolloff = 8` and it seems to work pretty well.

The shift is still existing when you really jump to the target but Leap and Hop does the same thing and at this point, the shifting is normal with a scrolloff option.

---

As always feedbacks are welcome !

**Comment by ziontee113** [comment]
Hi @woosaaahh , I like this implementation a lot :+1: 
Just one little problem with the extmarks keeps flashing as I type. Otherwise it feels really good.
I think with some fine tuning, it's gonna be wonderful.

**Comment by woosaaahh** [comment]
> Just one little problem with the extmarks keeps flashing as I type

That's one of the main problem I have with highlights. I tried to reduce this but it's not enough !

> I think with some fine tuning

I guess you're talking about the plugin, not your config.

> Leap is definitely faster with less keystrokes.

Leap definitely requires less keys !
However, you can get close by using `max_pattern_length = 2`, which will remove the need of typing the separator... but it doesn't work right now with multi_windows.

**Comment by ziontee113** [comment]
The main reason I like sj is that I have the flexibility to type as many search characters as I want. Which is both an upside and downside.

**Comment by woosaaahh** [comment]
I just pushed a fix for 'max_pattern_length' failing with 'multi_windows'.

For the flashing highlights, you mention the 'extmarks' which are for the labels.
I can't see the highlight flashing for the labels on my side but only labels constanstly updating for each character typed.

If this is what annoys you, we could add an option to only update them after the pattern has a given length ? 
_i.e._ if the pattern has at least 2 or 3 characters, update the labels.

If not, could you provide a screencast or video, please ? it might help a lot !

**Comment by ziontee113** [comment]
https://user-images.githubusercontent.com/102876811/199086564-bb4bf2f2-645d-4d24-a963-aff0f14c26ce.mp4

Here's the flashing issue I've talked about.

**Comment by woosaaahh** [comment]
Thanks for the video !

The flashing is due to the clearing before showing the labels.
If I don't clear, the buffer will keep "artifacts" but if I clear, too much flashing...
I have to find a better way but it will take time ! (vacations end today)

**Comment by ziontee113** [comment]
Take your time mate.

**Comment by woosaaahh** [comment]
Hi @ziontee113 !

I don't know if you heard but there is a new jump/search plugin in town : [flash.nvim](https://github.com/folke/flash.nvim)

It has multi-windows search, predefined pattern and a lot of cool features.
It works great "out-of-the-box" and it's also very tweakable !
Last but not least, it's done by folke so definitely a plus.

I'll need some time to get used to the labelling but since I started trying it yesterday, I really felt "at home" !

For the record, I'll still work sj but not a lot of new features. We'll see !

**Comment by ziontee113** [comment]
Hi @woosaaahh , thank you for the great work you've been doing. I'm still using sj atm. Great work man :+1:

**Comment by woosaaahh** [comment]
Hi !

I have good news. 

I'm working again on SJ and I'm pretty sure I finally solved the flickering issue with mult-windows search ! ( at least, "it works on my machine !" :smile: )

Expect a big release before next monday !

CC: @ziontee113

**Comment by woosaaahh** [comment]
Hi !

I just added support for multi-windows search.

However, it's not integraded in SJ code but as a separated plugin inside this project (`main` branch).
Since the beginning, SJ was built without multi-windows support in mind and that was a big mistake !
Most of SJ's code had to be rewritten to support this feature.

SJX is in early stage and doesn't support all features from SJ.
You can do single/multi windows search and define how labels are ordered (forward_search/relative_labels).

At some point SJ might be replaced by SJX.
Until then, both plugins are usable at the same time without conflicts.

---

Some things to be aware of : 

- SJX doesn't have the separator feature (imho, it's not needed anymore)
- when using the multi-windows option (`true` by default), the current window won't be used for a search (I'll add an exclude system later)
- when two windows are visible, only the other one (not the current one) will be used and only one-character labels will be needed. (a jump to the other window might be possible with only 2 keys)

---

Here is my own configuration for SJX : 
```lua
local sjx = require("sjx")
sjx.setup({
	prompt_prefix = "/",
})

vim.keymap.set({ "n" }, "!", sjx.run)

local sjx_highlights = {
	SjxLabel = { link = "SjLabel" },
	SjxMatches = { link = "SjMatches" },
	SjxNoMatches = { link = "SjNoMatches" },
	SjxOverlay = { link = "SjOverlay" },
}
for group, conf in pairs(sjx_highlights) do
	vim.api.nvim_set_hl(0, group, conf)
end
```

And here is the default configuration : 
```lua
{
	forward_search = true, -- if false, the search will be done from bottom to top
	multi_windows = true, -- if false, perform a search only for the current window
	pattern_type = "vim", -- how to interpret the pattern (lua, lua_plain, vim, vim_very_magic)
	prompt_prefix = "", -- if set, the string will be used as a prefix in the command line
	relative_labels = false, -- if true, labels are ordered from the cursor position, not from the top of the buffer
	use_overlay = true, -- if true, apply an overlay to better identify labels and matches

	--- labels used for each matches. (list of characters only)
	-- stylua: ignore
	labels = {
		"a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
		"n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
		"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
		"N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
		"0", "1", "2", "3", "4", "5", "6", "7", "8", "9", ",", ";", "!",
	},
}
```

---

As the work is far from done, I don't close this issue.

Any comments/critics/ideas/... are welcome !

CC: @ziontee113

**Comment by ziontee113** [comment]
> SJX doesn't have the separator feature (imho, it's not needed anymore)

Yeah I quickly switched to dynamic hints (hints as you type) as soon as that feature came out.

> Since the beginning, SJ was built without multi-windows support in mind and that was a big mistake !

We all learn along the way. I wrote my latest plugin 3 times over and it's still shit :joy: 

> SJX is in early stage and doesn't support all features from SJ yet.

I'd recommend you prioritize building what you actually find useful in your own workflow first. Don't feel the pressure to support everything or please everyone.

Build what you want, not what other people wants, unless they pay you :smile:

**Comment by woosaaahh** [comment]
Hi ! 

I'm using the multi-windows feature since released and it works fine for me.

As the feature is there, I close this issue.
