### ISSUE TITLE
[Feature] Use a keymap instead of the separator character

### ISSUE THREAD

**Issue by Runeword** [woosaaahh/sj.nvim#19]
Hey ! I wonder if you could add a keymap instead of the separator character.
So I could use the key `<Enter>` to split the user input in `<pattern>` and `<label>` for example.
Thanks !

**Comment by woosaaahh** [comment]
Hi !

If you want to use the `<Enter>`, you can already do this.

The problem is that the key used for the separator must not be part of the keymaps used while searching.

Here is a little sample config : 

```lua
require("sj").setup({
  separator = "\r", -- Press <Enter> to separate label from pattern
  keymaps = {
    validate = "<Tab>", -- Press <Tab> to jump to the focused match
  },
})
```
I'm not planning to implement this feature though.

If you get more than 3 :+1: until sunday, I might think about it more.

**Comment by Runeword** [comment]
Thanks for the tips ! I should have tried "\r"

**Comment by Runeword** [comment]
yes of course !
