### ISSUE TITLE
Error running config for sj.nvim: ...cal/share/nvim/site/pack/packer/start/sj.nvim/lua/sj.lua:63: invalid key

### ISSUE THREAD

**Issue by Runeword** [woosaaahh/sj.nvim#3]
**Versions used for**
 - Neovim v0.8.0-dev-1059-g2d6735d8c
 - SJ.nvim latest

**Describe the bug**
When I write the current buffer with :w, I got this error `Error running config for sj.nvim: ...cal/share/nvim/site/pack/packer/start/sj.nvim/lua/sj.lua:63: invalid key`

**To Reproduce**
Install sj.nvim with packer and use the configuration sample from the readme

**Expected behavior**
No error on buffer write

**Additional context**
There is no error when I remove the _highlights_ property in the sj.nvim configuration

**Comment by Runeword** [comment]
Thanks for your awesome plugin by the way

**Comment by Runeword** [comment]
For information, got it working by defining the colors with autocmd instead, this is the way I define most of the highlights anyway
`
    vim.api.nvim_create_augroup("sj", { clear = true })
    vim.api.nvim_create_autocmd("ColorScheme", {
      group = "sj",
      pattern = "*",
      callback = function()
        hi(0, 'SjLabel', { bg = '#ccff88', fg = 'black' })
        hi(0, 'SjSearch', { bg = '#77aaff', fg = 'black' })
      end
    })
`

**Comment by woosaaahh** [comment]
This is related to the last issue and is due to colorschemes clearing highlights.

I'm actually working on fixing this right now.
I'll push the fix as soon as possible !

**Comment by woosaaahh** [comment]
@Runeword This issue is fixed by b6cc0a00a0d425e25205797e0a29aa5730540144.

For this issue, the problem was due to `vim.api.nvim_get_hl_by_name()` which always returns `{ [true] = 6 }` 
when a highlight was cleared. I find this weird and would expect an empty table or `nil`.

In previous versions, this result was used to update SJ highlights by passing it to `vim.api.nvim_set_hl()`.
As the `true` key is invalid for highlights definition map, nvim raise an error.
